#pragma kernel WhiteNoise
#pragma kernel Bayer

#include "Random.cginc"

RWTexture2D<float4> Result;

float _Seed;
int _BayerLevel;

[numthreads(8,8,1)]
void WhiteNoise(uint3 id : SV_DispatchThreadID) {
    initRand((_Seed + id.x) * (_Seed * id.y) + (_Seed * id.x) * (_Seed + id.y));
    Result[id.xy] = randValue();
}

[numthreads(2,2,1)]
void Bayer(uint3 id : SV_DispatchThreadID) {
    Result[id.xy] = randValue();
}